language: python
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
script: 
  - ls
  - coverage run --source=src/ -m pytest src/tests
after_success: coveralls