language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install coverage
  - pip install pyyaml
  - pip install -U pytest
  - pip install robotframework
  - pip install python-coveralls

script: 

  - coverage run --source=./tests/
  - pytest ./ -v


after_success:
  - coveralls 


