language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install coverage
  - pip install -U pytest
  - pip install robotframework
  - pip install coveralls

script: 

  - cd tests/
  - cd test_files
  - python -m pytest dfa_test.py
  - coverage run -m pytest dfa_test.py
  - coverage report -m
  - coverage html


