language: python
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -U pytest
  - pip install pytest-pep8
  - pip install pytest-cov 
  - pip install pyyaml
  - pip install coveralls
  - pip install python-coveralls

script:
  - coverage run --source=src/ -m pytest src/tests
after_success:
  - coveralls