language: python
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -U pytest
  - pip install pytest-cov 
  - pip install pyyaml
  - pip install python-coveralls

script: 
  - ls
  - pytest --cov=src
  - coverage report -m 



after_success:
  - coveralls 


