language: python
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -U pytest
  - pip install pytest-pep8
  - pip install pytest-cov 
  - pip install pyyaml
  - pip install python-coveralls

script: 
  - pytest src/ --doctest-modules --pep8




after_success:
  - coveralls 


