language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install coverage
  - pip install -U pytest

script: 

  - cd tests/
  - pytest unit-test.py
  - python acceptance-test.py
