language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install coverage
  - pip install -U pytest
  - pip install robotframework
  - pip install python-coveralls

script: 

  - coverage run -m pytest ./ -v
  - coverage report -m
  - coverage html


after_success:
  - coveralls


