language: python
cache: pip

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
script: 
  - pytest --doctest-modules --pep8
  - coverage run --source=src/ -m pytest src/tests --pep8
after_success: coveralls