language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -U pytest
  - pip install pytest-cov 
  - pip install pyyaml
  - pip install python-coveralls

script: 
  - coverage run --source=. nfa.py /tests/nfa_test.py
  - coverage run --source=. dfa.py /tests/dfa_test.py
  - coverage report -m 



after_success:
  - coveralls 


